$schema: https://json.schemastore.org/aiconfig-1.0
description: Fill out a description about your AIConfig here.
metadata:
  default_model: gpt-3.5-turbo
  models:
    gpt-3.5-turbo:
      model: gpt-3.5-turbo
      temperature: 1
      top_p: 1
  parameters: {}
name: New AIConfig -- please rename me
prompts:
- input: Type anything you wish.
  name: prompt_1
  outputs: []
- input: 'Try passing data using parameters like {{order_by}}, and chaining prompts
    together, like this: {{prompt_1.output}}.'
  metadata:
    model: gpt-4
    parameters:
      order_by: geographic location
  name: prompt_2
  outputs: []
schema_version: latest
