$schema: https://json.schemastore.org/aiconfig-1.0
description:
  "Enter a description for this AIConfig. Learn about features in our [docs](https://aiconfig.lastmileai.dev/docs/category/overview)!

  "
metadata:
  default_model: gpt-3.5-turbo
  models:
    gpt-3.5-turbo:
      model: gpt-3.5-turbo
      temperature: 1
      top_p: 1
  parameters: {}
name: Untitled
prompts:
  - input: ""
    name: prompt_1
    outputs: []
  - input: ""
    metadata:
      model: gpt-4
      parameters: {}
    name: prompt_2
    outputs: []
schema_version: latest
